version: "3.7"
services:
    odoo10:
        image: odoo:10.0
        platform: linux/amd64
        container_name: odoo10
        depends_on:
            - postgresql
        tty: true
        stdin_open: true
        ports:
            - "8069:8069"
        volumes:
            - ./addons:/mnt/extra-addons
            - ./conf:/etc/odoo
        environment:
            - HOST=postgres10
    postgresql10:
        image: postgres:10.0
        container_name: postgres10
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo